name: native-release

on:
  push:
    branches:
      - master
    paths:
      - ORT_VERSION

jobs:
  native-release:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Native Release
    steps:
      - uses: actions/checkout@v6
      - uses: gradle/actions/wrapper-validation@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: oracle
          java-version: 25
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      # NOTE: the maven plugin uses the root project version to 'pick' the endpoint. this makes sure these artifacts do not go to snapshots.
      - name: Amend root project version
        run: |
          sed -i -E 's/version=.+/version=0.0.0/g' gradle.properties
          cat gradle.properties
      - name: Publish to maven central
        env:
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.PGP_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSWORD }}
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          ./gradlew --no-daemon -s publishOnnxruntimeCpuPublicationToSonatypeRepository publishOnnxruntimeGpuPublicationToSonatypeRepository closeSonatypeStagingRepository